api:
  # Get your API key from https://promptshield.io
  # Register for a Founder's Plan.
  # Or use OpenAI API key and set url to "https://api.openai.com/v1"
  url: "https://api.promptshield.io/v1"
  key: "${CHATTY_API_KEY}"
model:
  name: "openai/gpt-4o-mini"
  temperature: 0.7
  stream: true
ui:
  show_timestamps: true
logging:
  level: "info"
