api:
  url: "https://api-eu-fi-01.promptshield.io/v1"
  key: "ps_live_RKSji4CChAlCh9K4oOEW-2KRlbQKyMTl"
model:
  # name: "xai/grok-4-fast-non-reasoning"
  # name: "openai/gpt-4.1-mini"
  name: "google/gemini-flash-latest"
  temperature: 0.7
  stream: true
ui:
  show_timestamps: true
logging:
  level: "info"
